### ISSUE TITLE
Index exceeds matrix dimensions!

### ISSUE THREAD

**Issue by altaybrusan** [NVlabs/SNN#1]
I have this error:

Error in nlm (line 46)
            shifted_img_n = padded_img_n((windowHalfSearchSize + 1 +
            dy):(windowHalfSearchSize + ys + dy), ...

for 
J = nlm(I, 3, 4, 12, 0.3, 0.027, 0.8);

and 

I is 900*1278 of uint8

**Comment by ifrosio** [comment]
See last commit - I erroneously swapped the x/y dimensions of the image in the original implementation. fixed now.

**Comment by altaybrusan** [comment]
thanks
